// Local, reversible product demos. No account, upload, messaging or payment requests.
// The demos sit far below the fold, so they initialise on the visitor's first interaction.
function initGuapdDemos() {
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const quiet = () => matchMedia('(prefers-reduced-motion: reduce)').matches || document.documentElement.dataset.motion === 'paused';
const ease = 'cubic-bezier(.22,1,.36,1)';
function animate(el) { if (!quiet()) { el.getAnimations().forEach(a=>a.cancel()); el.animate([{opacity:.5,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:ease}); } }
function button(el, action, label) {
  if (!el) return;
  const b = document.createElement('button'); b.type='button'; b.className=el.className; b.innerHTML=el.innerHTML;
  if(label)b.setAttribute('aria-label',label); el.replaceWith(b); b.addEventListener('click',action); return b;
}
const live = document.createElement('div');live.className='demo-announcement sr-only';live.setAttribute('role','status');live.setAttribute('aria-live','polite');document.body.append(live);
function announce(text){live.textContent=text;}
const modal=document.createElement('dialog');modal.className='demo-dialog';modal.setAttribute('aria-labelledby','demo-title');modal.innerHTML='<button class="demo-close" aria-label="Close preview">×</button><span class="demo-kicker">INTERACTIVE PREVIEW</span><h2 id="demo-title"></h2><div class="demo-dialog-body"></div>';document.body.append(modal);
$('.demo-close',modal).onclick=()=>modal.close();
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
function show(title, content, setup) { $('#demo-title',modal).textContent=title;$('.demo-dialog-body',modal).replaceChildren();if(typeof content==='string')$('.demo-dialog-body',modal).innerHTML=content;else $('.demo-dialog-body',modal).append(content);setup?.($('.demo-dialog-body',modal));modal.showModal();animate($('.demo-dialog-body',modal)); }
function textPanel(title,text){const p=document.createElement('p');p.textContent=text;show(title,p);}
function revealDetail(stage) { if (!stage.classList.contains('demo-workspace-focus')) return; stage.classList.remove('demo-workspace-focus'); stage.style.minHeight=''; const toggle=stage.querySelector('.demo-stage-caption button[aria-pressed]');toggle.textContent='View workspace';toggle.setAttribute('aria-pressed','false'); stage.querySelector('.floating-sheet .demo-drag-handle')?.focus({preventScroll:true}); }
const originals=new Map();
let z=3;
function draggable(panel, handle, stage) {
  const reset=()=>{panel.style.translate='0px 0px';panel.dataset.dx='0';panel.dataset.dy='0';};
  originals.set(panel,reset);handle.classList.add('demo-drag-handle');handle.tabIndex=0;handle.setAttribute('role','group');handle.setAttribute('aria-label','Move panel. Drag, or use arrow keys. Press Home to reset.');
  let drag;
  function move(x,y){const r=panel.getBoundingClientRect(),s=stage.getBoundingClientRect();const dx=Number(panel.dataset.dx||0),dy=Number(panel.dataset.dy||0);const left=r.left-dx,top=r.top-dy;const visible=Math.min(r.width,s.width);x=Math.max(s.left-left+Math.min(0,s.width-r.width),Math.min(s.right-left-visible,x));y=Math.max(s.top-top+10,Math.min(s.bottom-top-Math.min(r.height,100)-10,y));panel.dataset.dx=x;panel.dataset.dy=y;panel.style.translate=`${x}px ${y}px`;}
  handle.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('button,input,a'))return;drag={x:e.clientX,y:e.clientY,dx:Number(panel.dataset.dx||0),dy:Number(panel.dataset.dy||0)};panel.style.zIndex=++z;handle.setPointerCapture(e.pointerId);panel.classList.add('is-dragging');});
  handle.addEventListener('pointermove',e=>{if(drag)move(drag.dx+e.clientX-drag.x,drag.dy+e.clientY-drag.y);});
  const end=()=>{drag=null;panel.classList.remove('is-dragging');};handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);handle.addEventListener('lostpointercapture',end);
  handle.addEventListener('keydown',e=>{const arrows={ArrowLeft:[-16,0],ArrowRight:[16,0],ArrowUp:[0,-16],ArrowDown:[0,16]};if(e.key==='Home'){e.preventDefault();reset();}else if(arrows[e.key]){e.preventDefault();move(Number(panel.dataset.dx||0)+arrows[e.key][0],Number(panel.dataset.dy||0)+arrows[e.key][1]);}});
}
$$('.product-stage').forEach((stage,i)=>{
 stage.setAttribute('role','region');stage.setAttribute('aria-label',['Interactive campaign brief','Interactive offer and contract','Interactive deliverable review','Interactive payment preview'][i]);
 const chrome=document.createElement('div');chrome.className='demo-stage-caption';chrome.innerHTML='<span>Interactive preview <span aria-hidden="true">·</span> Drag a panel to explore</span><button type="button">Reset view ↺</button>';stage.prepend(chrome);
 const focusButton=document.createElement('button');focusButton.type='button';focusButton.textContent='View workspace';focusButton.setAttribute('aria-pressed','false');chrome.insertBefore(focusButton,chrome.lastElementChild);focusButton.onclick=()=>{const height=stage.offsetHeight;const focused=stage.classList.toggle('demo-workspace-focus');stage.style.minHeight=focused?`${height}px`:'';focusButton.textContent=focused?'View detail':'View workspace';focusButton.setAttribute('aria-pressed',String(focused));$$('.product-window,.floating-sheet',stage).forEach(p=>originals.get(p)?.());animate($(focused?'.product-window':'.floating-sheet',stage));};
 $$('.product-window,.floating-sheet',stage).forEach(panel=>draggable(panel,$('.product-title,.sheet-eyebrow',panel),stage));
 $('button:last-child',chrome).onclick=()=>{$$('.product-window,.floating-sheet',stage).forEach(p=>originals.get(p)());announce('Panel positions reset.');};
 $$('.sheet-eyebrow>span',stage).forEach(el=>{el.textContent='⠿';el.setAttribute('aria-hidden','true');});
 $$('.tiny-info',stage).forEach(el=>button(el,()=>textPanel('One shared workspace','Explore this sample collaboration. Every change stays in this browser session.'),'About this preview'));
 $$('.window-tools>span',stage).filter(el=>!el.classList.contains('avatar')).forEach(el=>button(el,()=>show('Shared workspace','<p>Everyone sees the same brief, feedback and payment status.</p><div class="demo-person">Ava Williams <span>Brand · Can edit</span></div><div class="demo-person">Maya Chen <span>Creator · Can edit</span></div><p class="demo-muted">This is a local preview. No invitations are sent.</p>'),'View workspace members'));
});
// Editable structured brief, selection, filter, search and density.
const brief=$('#workflow-brief');
$$('.field-list b',brief).forEach((el,i)=>{const input=document.createElement('input');input.className='demo-field';input.value=el.textContent;input.setAttribute('aria-label',['Deliverables','First draft date','Campaign rate','Payment split','Revision allowance'][i]);el.replaceWith(input);input.addEventListener('change',()=>{announce('Brief updated in this preview.');$('.brief-sheet .sheet-footer>span').textContent='Changes saved locally';});});
const names=['Maya Chen','Jules Martin','Sam Rivera','Alex Morgan','Noor Patel'];
$$('.table-row:not(.table-head)',brief).forEach((row,i)=>{const cell=$('span',row);const label=document.createElement('button');label.className='demo-row-name';label.textContent=names[i];cell.replaceChildren(label);label.onclick=()=>{revealDetail($('.product-stage',brief));$('.sheet-person>span:nth-child(2)',brief).innerHTML='';$('.sheet-person>span:nth-child(2)',brief).append(document.createTextNode(names[i]));const small=document.createElement('small');small.textContent='Creator';$('.sheet-person>span:nth-child(2)',brief).append(small);$$('.table-row',brief).forEach(r=>r.classList.toggle('demo-row-selected',r===row));animate($('.brief-sheet',brief));};});
button($('.brief-sheet .mock-button'),e=>{const sent=e.currentTarget.dataset.sent==='true';e.currentTarget.dataset.sent=String(!sent);e.currentTarget.textContent=sent?'Send brief ↗':'Edit brief ↶';$('.sheet-person .badge',brief).textContent=sent?'Awaiting approval':'Brief shared · Demo';$('.brief-sheet .sheet-footer>span').textContent=sent?'Draft restored':'Shared in this preview';animate($('.sheet-person',brief));announce(sent?'Brief returned to draft.':'Sample brief shared. No message was sent.');});
const briefFilter=button($('.tool-pill',brief),e=>{const filtered=e.currentTarget.dataset.filtered!=='true';e.currentTarget.dataset.filtered=String(filtered);e.currentTarget.innerHTML=filtered?'Agreed collaborations ⌄':'All collaborations ⌄';$$('.table-row:not(.table-head)',brief).forEach(r=>r.hidden=filtered&&!r.textContent.includes('Agreed'));announce(filtered?'Showing agreed collaborations.':'Showing all collaborations.');});
button($$('.tool-pill',brief)[1],e=>{const dense=$('.product-table',brief).classList.toggle('demo-compact');e.currentTarget.textContent=dense?'⊞ Comfortable view':'⊞ Compact view';});
const searchEl=$('.toolbar-search',brief);const briefSearch=document.createElement('input');briefSearch.className='demo-search';briefSearch.placeholder='Search creators';briefSearch.setAttribute('aria-label','Search creators');searchEl.replaceWith(briefSearch);briefSearch.addEventListener('input',()=>{$$('.table-row:not(.table-head)',brief).forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(briefSearch.value.toLowerCase()));briefFilter.dataset.filtered='false';briefFilter.textContent='All collaborations ⌄';});
button($('.window-bottom',brief),()=>{show('Add a sample collaboration','<form class="demo-form"><label>Creator name<input name="name" required maxlength="50" placeholder="e.g. Jordan Lee"></label><button class="mock-button" type="submit">Add to preview</button></form>',body=>{$('form',body).onsubmit=e=>{e.preventDefault();const name=$('input',body).value.trim();if(!name)return;const row=document.createElement('div');row.className='table-row';for(const text of [name,'1 Reel','Oct 28','Draft']){const span=document.createElement('span');span.textContent=text;row.append(span);}$('.product-table',brief).append(row);modal.close();announce('Sample collaboration added.');};});});
// Contract tabs stay in a fixed workspace; no page navigation or resized sections.
const terms=$('#workflow-terms'),negotiation=$('.negotiation',terms);
const termsPanel=document.createElement('div');termsPanel.className='demo-tab-panel';termsPanel.hidden=true;negotiation.after(termsPanel);
$$('.workspace-tabs>span',terms).forEach(el=>{const name=el.textContent;const b=button(el,()=>{$$('.workspace-tabs button',terms).forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});negotiation.hidden=name!=='Offers & contract';termsPanel.hidden=name==='Offers & contract';const contents={Overview:'<h4>Forme × Maya Chen</h4><p>Everyday essentials</p><div class="demo-summary-grid"><div>Campaign value<strong>₹45,000</strong></div><div>Final delivery<strong>October 18</strong></div></div><p>2 Reels · 3 Stories · 2 revision rounds</p>',Deliverables:'<h4>Everything, delivered.</h4><p>✓ Morning routine — Reel 01</p><p>✓ Everyday essentials — Reel 02</p><p>✓ Story series — 3 frames</p>',Payments:'<h4>Two clear milestones.</h4><p>✓ On signing <b>₹22,500</b></p><p>✓ On final approval <b>₹22,500</b></p><p>Paid in full · ₹45,000</p>'};termsPanel.innerHTML=contents[name]||'';animate(name==='Offers & contract'?negotiation:termsPanel);});b.setAttribute('aria-pressed',String(b.classList.contains('selected')));});
button($('.signed-banner>span',terms),()=>show('Collaboration agreement','<p>Forme × Maya Chen · Sample contract</p>'+$('.contract-lines',terms).outerHTML+$('.signatures',terms).outerHTML+'<p class="demo-muted">Illustrative agreement only. No contract is signed through this preview.</p>'),'View contract');
// Review workspace: switch files, play a short CSS product preview, revisions and approval.
const review=$('#workflow-review');let rounds=1,approved=false,activeAsset=0;
const assetStates=[{rounds:1,approved:false},{rounds:0,approved:true}];
function updateReview(){ assetStates[activeAsset]={rounds,approved}; const done=assetStates.filter(s=>s.approved).length; $$('.workspace-tabs em',review).forEach((el,i)=>el.textContent=[2,2-done,done][i]); const approveButton=$('.review-sheet .mock-button:not(.subtle-button)',review); if(approveButton)approveButton.textContent=approved?'Undo approval ↶':'Approve file ✓'; const revisionButton=$('.subtle-button',review);if(revisionButton)revisionButton.setAttribute('aria-disabled',String(rounds>=2)); $('.revision-meter b',review).textContent=`${rounds} of 2 used`;$$('.revision-meter i',review).forEach((x,i)=>x.style.background=i<rounds?'#92adf0':'#edf0f5');$('.resolved-note',review).textContent=approved?'✓ File approved in this preview':rounds===2?'↻ Final revision requested · 2 of 2 rounds used':'✓ Feedback addressed in version 2';const status=$$('.asset-caption .badge',review)[activeAsset];status.textContent=approved?'Approved':'In review';status.className=`badge ${approved?'green-badge':'blue-badge'}`;}
$$('.asset-card',review).forEach((card,i)=>{
 button($('.asset-caption>b',card),()=>{revealDetail($('.product-stage',review));activeAsset=i;$('.review-sheet h4',review).textContent=$('.asset-caption button',card).textContent;approved=assetStates[i].approved;rounds=assetStates[i].rounds;updateReview();animate($('.review-sheet',review));},`Review ${$('.asset-caption>b',card).textContent}`);
 button($('.play-icon',card),e=>{const play=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',String(play));e.currentTarget.textContent=play?'Ⅱ':'▶';e.currentTarget.setAttribute('aria-label',play?'Pause product preview':'Play product preview');$('.asset-art',card).classList.toggle('demo-playing',play);},'Play product preview');
});
$$('.workspace-tabs>span',review).forEach((el,i)=>{const b=button(el,()=>{$$('.workspace-tabs button',review).forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});$$('.asset-card',review).forEach(card=>{card.hidden=i===1?$('.badge',card).textContent!=='In review':i===2?$('.badge',card).textContent!=='Approved':false;});animate($('.asset-grid',review));});b.setAttribute('aria-pressed',String(i===0));});
button($('.subtle-button',review),()=>{if(rounds>=2){announce('Both agreed revision rounds have been used.');return;}rounds++;approved=false;updateReview();animate($('.revision-meter',review));announce('Final revision requested in the preview.');});
button($('.review-sheet .mock-button:not(.subtle-button)',review),e=>{approved=!approved;e.currentTarget.textContent=approved?'Undo approval ↶':'Approve file ✓';updateReview();animate($('.resolved-note',review));announce(approved?'File approved in preview.':'Approval undone.');});
button($('.file-chip',review),()=>textPanel('Version 2','morning-routine-v2.mp4 · Product preview updated with a longer opening shot. Select Play on the asset card to preview the visual.'));
updateReview();
const comment=document.createElement('form');comment.className='demo-comment-form';comment.innerHTML='<label class="sr-only" for="demo-comment">Add review feedback</label><input id="demo-comment" maxlength="180" placeholder="Add a comment…" required><button aria-label="Post preview comment">↑</button>';$('.review-sheet .sheet-footer',review).before(comment);comment.onsubmit=e=>{e.preventDefault();const value=$('input',comment).value.trim();if(!value)return;$('.resolved-note',review).textContent=`You: ${value}`;$('input',comment).value='';announce('Comment added to the local preview.');animate($('.resolved-note',review));};
button($('.upload-bar',review),()=>{show('Add a sample version','<p>Try the upload flow with a built-in sample. No personal files are uploaded.</p><button class="mock-button">Add version 3</button>',body=>{$('button',body).onclick=()=>{$('.file-chip',review).textContent='▧ morning-routine-v3.mp4 ↗';$('.resolved-note',review).textContent='✓ Version 3 added · Ready for review';modal.close();announce('Sample version 3 added.');};});})?.append(Object.assign(document.createElement('span'),{className:'sr-only',textContent:' Add a sample version'}));
// Payment timeline is an explicit, reversible simulation.
const payment=$('#workflow-payments');let milestone=4;
const replay=document.createElement('button');replay.className='demo-replay';replay.textContent='Replay payment journey ↺';$('.payment-sheet .payment-total',payment).after(replay);
replay.onclick=()=>{milestone=milestone===4?0:milestone+1;const paid=milestone>=4?45000:milestone>=2?22500:0;const money=n=>'₹'+n.toLocaleString('en-IN');const totals=$$('.money-summary b',payment);totals[1].textContent=money(paid);totals[2].textContent=money(45000-paid);$('.payment-sheet .payment-total',payment).innerHTML=money(paid)+' <span>received</span>';$$('.product-table .table-row:not(.table-head)',payment).forEach((row,i)=>{const settled=milestone>=(i===0?2:4);$('.badge',row).textContent=settled?'✓ Paid':'Pending';$('.badge',row).className='badge '+(settled?'green-badge':'gray-badge');});$$('.payment-timeline>div',payment).forEach((row,i)=>{row.classList.toggle('demo-pending',i>=milestone);$('i',row).textContent=i<milestone?'✓':'·';});$('.payment-sheet h4',payment).textContent=['Terms ready.','Agreed together.','Halfway there.','Work approved.','All settled.'][milestone];$('.payment-sheet .sheet-subtitle',payment).textContent=['Start with a clear agreement.','Both sides know what comes next.','Upfront payment received.','The final milestone is ready.','The work is done. So is the payment.'][milestone];replay.textContent=milestone===4?'Replay payment journey ↺':'Next milestone →';animate($('.payment-timeline',payment));announce(`Payment preview: ${milestone} of 4 milestones complete.`);};
button($('.receipt-link',payment),()=>show('Payment receipt','<p class="demo-muted">Sample receipt · Forme × Maya Chen</p><div class="demo-person">Signing payment <b>₹22,500</b></div><div class="demo-person">Final approval <b>₹22,500</b></div><div class="demo-person">Total paid <b>₹45,000</b></div><p>October 18, 2026 · Paid in full</p><p class="demo-muted">Preview only. No financial transaction has taken place.</p>'));
$$('.tool-pill',payment).forEach((el,i)=>button(el,e=>{if(i===0){const final=e.currentTarget.dataset.final!=='true';e.currentTarget.dataset.final=String(final);e.currentTarget.textContent=final?'Final payment ⌄':'All transactions ⌄';$$('.table-row:not(.table-head)',payment)[0].hidden=final;}else{$('.product-table',payment).classList.toggle('demo-compact');e.currentTarget.textContent=$('.product-table',payment).classList.contains('demo-compact')?'⊞ Comfortable view':'⊞ Compact view';}}));
// Dashboard rows reveal a local detail view; reordering has keyboard-friendly buttons.
$$('.dash-table tbody tr').forEach(row=>{const div=$('td:first-child>div',row),name=div.firstChild.textContent,campaign=$('small',div).textContent;const b=document.createElement('button');b.className='demo-row-name';b.textContent=name;div.firstChild.replaceWith(b);b.onclick=()=>show(name+' collaboration',`<p>${campaign}</p><div class="demo-person">Status <b>${$('td:nth-child(2)',row).textContent}</b></div><div class="demo-person">Next date <b>${$('td:nth-child(3)',row).textContent}</b></div><div class="demo-person">Campaign value <b>${$('td:nth-child(4)',row).textContent}</b></div><div class="demo-actions"><button class="tool-pill" data-move="up">Move up ↑</button><button class="tool-pill" data-move="down">Move down ↓</button></div><p class="demo-muted">Reorder your workspace without changing any campaign details.</p>`,body=>{$$('[data-move]',body).forEach(btn=>btn.onclick=()=>{const other=btn.dataset.move==='up'?row.previousElementSibling:row.nextElementSibling;if(other){btn.dataset.move==='up'?other.before(row):other.after(row);announce(`${name} moved ${btn.dataset.move}.`);}else announce('Already at the edge of the list.');});});row.draggable=true;row.addEventListener('dragstart',e=>{row.classList.add('demo-drag-row');e.dataTransfer.setData('text/plain',name);});row.addEventListener('dragend',()=>row.classList.remove('demo-drag-row'));row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();const moving=$('.demo-drag-row');if(moving&&moving!==row){row.before(moving);animate(row);announce('Collaborations reordered.');}});});
const months=['May','June','July','August','September','October'],earnings=['₹22,500','₹34,500','₹28,500','₹51,000','₹44,250','₹75,000'];
const chart=$('.earnings-chart');chart.setAttribute('role','group');chart.setAttribute('aria-label','Illustrative monthly earnings. Select a month.');$$('i',chart).forEach((el,i)=>{const b=button(el,()=>{$('.earnings-card>strong').innerHTML=earnings[i]+' <span>received</span>';$('.earnings-card .dash-card-title>span').textContent=months[i];$$('button',chart).forEach(x=>x.setAttribute('aria-pressed',String(x===b)));announce(`${months[i]}: ${earnings[i]} received in the sample data.`);},`${months[i]}: ${earnings[i]}`);b.style.setProperty('--bar',el.style.getPropertyValue('--bar'));b.setAttribute('aria-pressed',String(i===5));});
window.addEventListener('resize',()=>originals.forEach(reset=>reset()));
}
{
  const triggers = ['scroll', 'wheel', 'touchstart', 'pointerdown', 'keydown'];
  let started = false;
  const start = () => { if (started) return; started = true; triggers.forEach(t => removeEventListener(t, start)); initGuapdDemos(); };
  triggers.forEach(t => addEventListener(t, start, { passive: true }));
  if (scrollY > 0 || location.hash) start();
}
